config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :instructors do 
      resources :cohorts
  end
  resources :students do
    resources :student_tests
  end

  resources :cohorts do 
    resources :students
  end

  #patch 'some route', to: "students#change_students_cohort"

  resources :sessions
  get '/instructor_login', to: "sessions#new_instructor"
  post '/sessions', to: "sessions#create"
  get '/student_login', to: "sessions#new_student"
  get '/logout', to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cohort.rb
class Cohort < ApplicationRecord
	has_many :students
	has_many :cohort_instructors
	has_many :cohorts, through: :cohort_instructors
	has_many :student_tests, through: :students

	def new_student
	end

	def new_student=(name)
		self.students << Student.create(name:name, cohort_id: self.id)
		# if student.valid?
		# 	student.save
		# end
	end
end

app/models/cohort_instructor.rb
class CohortInstructor < ApplicationRecord
	belongs_to :cohort 
	belongs_to :instructor
end

app/models/instructor.rb
class Instructor < ApplicationRecord
	has_many :cohort_instructors
	has_many :cohorts, through: :cohort_instructors
	has_many :students, through: :cohorts

	has_secure_password

	validates :name, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
	belongs_to :cohort, optional: true
	has_many :student_tests
	has_many :tests, through: :student_tests
	has_many :instructors, through: :cohort

	has_secure_password optional: true

	validates :name, presence: true

end

app/models/student_test.rb
class StudentTest < ApplicationRecord
	belongs_to :student
	belongs_to :test
	validates :student_id, uniqueness: { scope: :test_id,
    message: "Each student takes each test one time" }
end

app/models/test.rb
class Test < ApplicationRecord
	has_many :student_tests
	has_many :students, through: :student_tests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # helper_method :current_user

  # def current_user 
  # 	user = ""
  # 	if session[:instructor_id] 
  # 		user 
  # 		session[:student_id]
  # end
end

app/controllers/cohort_instructors_controller.rb
class CohortsInstructorController < ApplicationController


end

app/controllers/cohorts_controller.rb
class CohortsController < ApplicationController
	def index
		@cohorts = Cohort.all
	end

	def show
		@cohort = Cohort.find(params[:id])
	end

	def new
		@cohort = Cohort.new
	end

	def create
		@cohort = Cohort.new(cohort_params)
		if @cohort.save
			redirect_to cohorts_path
		else
			render :new
		end
	end

	def edit
		@cohort = Cohort.find(params[:id])
	end

	def update
		@cohort = Cohort.find(params[:id])
		@cohort.update(cohort_params)
		redirect_to cohort_path(@cohort)
	end

	private

	def cohort_params
		params.require(:cohort).permit(:name, :new_student, student_ids: [])
	end

end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
	
	before_action :set_instructor, only: [:show, :edit, :update, :destroy]

	def index
		@instructors = Instructor.all
	end

	def show
		# @students = Student.all.select { |student| student.cohort_id == @instructor.cohort_id}
	end

	def new
		@instructor = Instructor.new
	end

	def create
		@instructor = Instructor.new(instructor_params)
		if @instructor.valid?
			@instructor.save
			session[:instructor_id] = @instructor.id
			redirect_to instructor_path(@instructor)
		else
			render :new
		end
	end

	def edit
	end

	def update
		@instructor.update(instructor_params)
		if @instructor.save
			redirect_to instructor_path(@instructor)
		else 
			render :edit
		end
	end

	def remove_cohort

	end

	def destroy
		CohortInstructor.find().destroy
		flash[:success] = "Cohort deleted"
    	redirect_to instructor_path(session[:instructor_id])
	end


	private

	def instructor_params
		params.require(:instructor).permit(:name, :instructor_feedback, :password, cohort_ids: [])
	end

	def set_instructor
		@instructor = Instructor.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController<ApplicationController
  

  def create

    if params[:student]
        @student = Student.find_by(name: params[:student][:name])
        @student.authenticate(params[:student][:password])
        session[:student_id] = @student.id
        redirect_to student_path(@student)
    elsif params[:instructor]
        @instructor = Instructor.find_by(name: params[:instructor][:name])
        @instructor.authenticate(params[:instructor][:password])
        session[:instructor_id] = @instructor.id
        redirect_to instructor_path(@instructor)
    else
      redirect_to root_path
    end 
  end
  
  def destroy
    session.destroy

    redirect_to '/'
  end
end

app/controllers/student_tests_controller.rb
class StudentTestsController < ApplicationController

	before_action :set_student_test, only: [:show, :edit, :update, :destroy]

	def index
		@student_tests = StudentTest.all
	end

	def show
	end

	def new
		@student_test = StudentTest.new
		@student = Student.find(params[:student_id])
	end

	def edit
		@student_test = StudentTest.find(params[:id])
		@student = @student_test.student
	end

	def create
		@student_test = StudentTest.create(student_test_params)
		@student = @student_test.student

		if @student_test.save
			redirect_to student_path(@student)
		else
			redirect_to new_student_student_test_path
		end

	end

	

	def update

		@student_test.update(student_test_params)

		if @student_test.save
			redirect_to student_student_path(@student_test.student)
		else 
			render edit_student_student_test_path
		end
	end



	private

	def student_test_params
		params.require(:student_test).permit(:name, :student_id, :graded, :instructor_feedback, :test_id, :meeting?, :id)
	end

	def set_student_test
		@student_test = StudentTest.find(params[:id])
	end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	
	before_action :set_student, only: [:show, :edit, :update, :destroy]

	def index
		@students = Student.all
		@cohorts = Cohort.all
	end

	def show
		@student_tests = StudentTest.where(student_id: session[:student_id])
		# if !@student(params[:id])
		# 	flash[:message] = "You are not #{@student.name}! GTFO!"
		# end
	end


	def new
		@student = Student.new
		@cohort_id = params[:cohort_id]
	end

	def create
		@student = Student.new(student_params)

		if @student.save
			session[:user_id] = @student.id
			redirect_to student_path(@student)
		else
			render :new
		end

	end

	def edit
		if session[:student_id]
			redirect_to student_path(@student)
		end
	end

	def update
		@student.update(student_params)
		if @student.save
			redirect_to student_path(@student)
		else 
			render :edit
		end
	end

	def destroy
		@student.destroy
	end

	private

	def student_params
		params.require(:student).permit(:name, :cohort_id, :password)
	end

	def set_student
		@student = Student.find(params[:id])
	end
end

app/controllers/welcome_controller.rb
class WelcomeController<ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cohort_instructors_helper.rb
module CohortInstructorsHelper
end

app/helpers/cohorts_helper.rb
module CohortsHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/views/cohorts/_form.html.erb
<%= form_for @cohort do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %><br>
 <%= f.submit "Create Cohort"%>
<% end %>

app/views/cohorts/edit.html.erb
<%= render 'form' %>

app/views/cohorts/index.html.erb
<%@cohorts.each do |c| %>
	<h1><%= link_to c.name, cohort_path(c) %></h1>
<%end%>

app/views/cohorts/new.html.erb
<%= render 'form' %>

app/views/cohorts/show.html.erb
<% if session[:instructor_id] %>
<% @cohort.students.each do |s| %>
	<h1><%= link_to s.name.capitalize, student_path(s)%><br></h1>
	<% s.student_tests.each do |t| %>
		<li><%= link_to t.test.name.capitalize, edit_student_student_test_path(t)%><br></li>
	<%end%>

	<label>Change cohort?</label>
	<%= form_for s do |f|%>
		<%=f.collection_select :cohort_id, Cohort.all, :id, :name %>
		<%=f.submit%>
	<% end %>
<%end%><br>
<%= link_to "add a student", new_cohort_student_path(@cohort.id)%><br>
<%= link_to "home", instructor_login_path%>

<% else %>
<% @cohort.students.each do |s| %>
	<h1><%= s.name.capitalize%><br></h1>
<%end%>

<%end%>

app/views/instructors/edit.html.erb
<%= form_for @instructor do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%= f.collection_check_boxes(:cohort_ids, Cohort.all, :id, :name)%>
 <%= f.submit "Update account"%>
<% end %>

app/views/instructors/index.html.erb
-

app/views/instructors/new.html.erb
<%= form_for @instructor do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%= f.collection_check_boxes(:cohort_ids, Cohort.all, :id, :name)%>
 <%= f.submit "Create Account"%>
<% end %>

app/views/instructors/show.html.erb
<h1><%= @instructor.name %></h1><br>

<h1> My Cohorts </h1>
<% @instructor.cohorts.each do |c| %>
	<h1><%= link_to "#{c.name}", instructor_cohort_path(@instructor,c)%></h1>
<% end %>


<%= link_to "Create a new Cohort", new_instructor_cohort_path(@instructor.id) %><br>
<%= link_to "Edit your account", edit_instructor_path %><br>
<%= link_to "logout", logout_path%>

app/views/student_tests/_form.html.erb
<%=@student.name%>

<%= form_for ([@student, @student_test]) do |f| %>
<%= f.label :name %>
<%= f.collection_select :test_id, Test.all, :id, :name %><br>
<%= f.hidden_field :student_id, :value => @student.id %>
<%= f.label :graded %>
<%= f.select :graded, ['pass', 'retake', 'pending']%><br>
<%= f.label :instructor_feedback %>
<%= f.text_area :instructor_feedback %><br>
<%= f.label :meeting? %>
<label>Yes</label>
<%= f.radio_button("meeting?", "yes") %>
<label>No</label>
<%= f.radio_button("meeting?", "no") %>
<%= f.submit%>
<% end %>

app/views/student_tests/edit.html.erb
Edit Test for 
<%= render :partial => "form" %>

app/views/student_tests/index.html.erb
<%@student_tests.each do |t| %>
	<%= link_to t.name, edit_student_test_path  %>
<%end%>

app/views/student_tests/new.html.erb
Create test for
<%= render :partial => "form" %>

app/views/student_tests/show.html.erb
<%= @student_test.name %><br>
<%= @student_test.student.name %><br>
<%= @student_test.graded %><br>
<%= @student_test.meeting? %><br>
<%= @student_test.instructor_feedback %>

app/views/students/edit.html.erb
edit.html.erb

app/views/students/index.html.erb
<h2>Students</h2>
<%@cohorts.each do |c| %>
	<p><%= c.name %></p>
	<%c.students.each do |s| %>
		<%= link_to s.name, new_student_student_test_path(s)%><br>
	<%end%>
<%end%>

app/views/students/new.html.erb
<%= form_for @student do |f| %>
 <%= f.label :name %>
 <%= f.text_field :name %>
 <%= f.label :password %>
 <%= f.password_field :password %>
 <%= f.hidden_field :cohort_id, { :value => @cohort_id} %>
 <%= f.submit "Create Account"%>
<% end %>

app/views/students/show.html.erb
<h1><%= @student.name.capitalize %></h1><br>
<h2><%= @student.cohort.name.capitalize %></h2><br>
<%= form_for @student do |f|%><br>
		<%=f.collection_select :cohort_id, Cohort.all, :id, :name %>
		<%= f.submit 'change cohort', :class => "ui button" %>
	<% end %>

<% @student.student_tests.each do |t| %>
	<h2><%= t.test.name.capitalize %></h2>
	<h3>Grade: <%= t.graded %></h3>
	<h3>Feedback:  <%= t.instructor_feedback %></h3>
	<h3>Meeting Scheduled?  <br><% if t.meeting? %>
							<%= "Yes!" %>
							<% else %>
							<%= "Nope!" %>
							<%end%></h3><br>

	<% if session[:instructor_id] %>
	<%= link_to "Edit Test", edit_student_student_test_path(t) %>
	<%end%>
<% end %><br><br><br>

<%= link_to "my cohort", cohort_path(@student.cohort_id) %><br>
<% if session[:student_id] %>
<%= link_to "logout", logout_path %><br>
<% end %>

<% if session[:instructor_id] %>
<%= link_to "add test", new_student_student_test_path(@student) %>

<%end%>

app/views/welcome/index.html.erb
<h1>Welcome to the Flatiron Assessment App!</h1>

<h2><%= link_to "Instructor", instructor_login_path%></h2>
<h2><%= link_to "Student", student_login_path%></h2>